apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: scalable-node-app-example-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: scalable-node-app-example
    spec:
      containers:
      - name: scalable-node-app-example
        image: johnsusek/scalable-node-app-example
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
