apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: scalable-node-app-example
  namespace: default
spec:
  maxReplicas: 5
  minReplicas: 1
  scaleTargetRef:
    apiVersion: extensions/v1
    kind: Deployment
    name: scalable-node-app-example-deployment
  targetCPUUtilizationPercentage: 1
