apiVersion: v1
kind: Service
metadata:
  name: scalable-node-app-example
  labels:
    app: scalable-node-app-example
spec:
  selector:
    app: scalable-node-app-example
  ports:
  - port: 8080
    protocol: TCP
    nodePort: 30080
  type: LoadBalancer
